apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels: 
        app: postgre
    spec: 
      containers:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES__DB
              value: fakeshop
          env:
            - name: POSTFRES_USER           
              value: fakeshop
          env:
            - name: POSTGRES_PASSWORD
              value: Pg1234
---
apiVersion: v1 
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: posgre
  ports:
  - port: 5432
    targetPort: 5432

